services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=aaa
      - POSTGRES_DB=zimple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:aaa@postgres:5432/zimple_bank?sslmode=disable
      - GIN_MODE=release
    depends_on:
      - postgres