apiVersion: v1
kind: Service
metadata:
  name: zimple-bank-api-service
spec:
  selector:
    app: zimple-bank-api
  ports:
    - protocol: TCP
      port: 80 # on which the server will listen to incoming request
      targetPort: 8080 # port of the container where the request will be sent to
  type: LoadBalancer # change to ClusterIP if use Ingress