name: Run unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:16
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: aaa
            POSTGRES_DB: zimple_bank
          ports:
            - 5432:5432
          # Set health checks to wait until postgres has started
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
